# -*- coding: utf-8 -*-
"""Copy of Proyek Capstone Analisis Data CC26-PRU474.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNOqtCwk7SXlSOaiDFALT5ODZO-oe_3n

# Proyek Analisis Data: Mental Health Dataset
- **Nama:** [Input Nama]
- **Email:** [Input Email]
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis

1.	Bagaimana korelasi antara menghabiskan waktu di dalam ruangan (Days Indoors) dengan tingkat pertumbuhan stres (Growing Stress) dan munculnya gangguan kebiasaan tidur (Changes Habits)?
2.	Apakah jenis pekerjaan (Occupation) atau status wirausaha (self-employed) berpengaruh signifikan terhadap probabilitas seseorang mencari pengobatan atau terapi (Treatment) kesehatan mental?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import spearmanr, chi2_contingency
import statsmodels.api as sm

"""## Data Wrangling

### Gathering Data
"""

url = "https://drive.google.com/uc?export=download&id=1RBs4qfgFFhl0DJwh5FZbUipMZVKh6Oo5"
df = pd.read_csv(url)
df.head()

"""**Insight:**

Fitur dalam dataset:
1.  Timestamp
2.  Gender
3.  Country
4.  Occupation
5.  self_employed
6.  family_history
7.  treatment
8.  Days_Indoors
9.  Growing_Stress
10.  Changes_Habits
11.  Mental_Health_History
12.  Mood_Swings
13.  Coping_Struggles
14.  Work_Interest
15.  Social_Weakness
16.  mental_health_interview
17.  care_options

### Assessing Data
"""

# data type

df.info()

# missing value

df.isna().sum()

# duplicate data

print("Jumlah duplikasi: ", df.duplicated().sum())

# inaccurate value

df.describe()

"""**Insight:**
- Mayoritas tipe data salah
- 5202 missing value (...% dari total data) pada kolom self_employed
- 363 duplicated data (...% dari total data)
- Inacurate data belum pasti karena tipe data banyak yang salah

### Cleaning Data
"""

datetime_columns = ["Timestamp"]

for column in datetime_columns:
    df[column] = pd.to_datetime(df[column])

df.info()

binary_map = {'Yes': True, 'No': False}

df['family_history'] = df['family_history'].map(binary_map)
df['treatment'] = df['treatment'].map(binary_map)
df['Coping_Struggles'] = df['Coping_Struggles'].map(binary_map)

df.info()

"""Semua tipe data sudah benar"""

# Mengatasi missing value

df[df.self_employed.isna()]

df.self_employed.value_counts()

df.fillna(value="No", inplace=True)
df.isna().sum()

# Menangani duplicate data

df.drop_duplicates(inplace=True)
print("Jumlah duplikasi: ", df.duplicated().sum())

df.describe(include='all')

"""**Insight:**
- xxx
- xxx

## Exploratory Data Analysis (EDA)

### Univariate
"""

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x="Gender")
plt.title("Jumlah Pengguna Berdasarkan Gender")
plt.show()

plt.figure(figsize=(5,4))
sns.countplot(data=df, x="treatment")
plt.title("Distribusi Treatment (Target)")
plt.show()

plt.figure(figsize=(12,5))
sns.countplot(data=df, x="Days_Indoors")
plt.title("Distribusi Days Indoors")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,5))
sns.countplot(data=df, x="Occupation")
plt.title("Distribusi Occupation")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(5,4))
sns.countplot(data=df, x="Growing_Stress")
plt.title("Distribusi Growing Stress")
plt.show()

plt.figure(figsize=(5,4))
sns.countplot(data=df, x="Changes_Habits")
plt.title("Distribusi Changes Habits")
plt.show()

"""Bivariate

Pertanyaan 1
"""

plt.figure(figsize=(12,5))
sns.countplot(data=df, x="Days_Indoors", hue="Growing_Stress")
plt.title("Days Indoors vs Growing Stress")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,5))
sns.countplot(data=df, x="Days_Indoors", hue="Changes_Habits")
plt.title("Days Indoors vs Changes Habits")
plt.xticks(rotation=45)
plt.show()

pd.crosstab(df['Days_Indoors'], df['Growing_Stress'], normalize='index') * 100

pd.crosstab(df['Days_Indoors'], df['Changes_Habits'], normalize='index') * 100

"""Pertanyaan 2"""

plt.figure(figsize=(14,6))
sns.countplot(data=df, x="Occupation", hue="treatment")
plt.title("Occupation vs Treatment")
plt.xticks(rotation=45)
plt.show()

pd.crosstab(df['Occupation'], df['treatment'], normalize='index') * 100

"""Multivariate"""

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df.groupby(['Occupation', 'Growing_Stress'])['treatment'].value_counts(normalize=True)

"""**Insight:**
- xxx
- xxx

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""



"""### Pertanyaan 2:"""



"""**Insight:**
- xxx
- xxx

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1
- Conclution pertanyaan 2
"""